security:
    always_authenticate_before_granting: true

    providers:
        our_db_provider:
            entity:
                class: App\Entity\User
                property: username
    encoders:
        App\Entity\User:
            algorithm: sha1
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:    ^/
            anonymous: ~
            provider: our_db_provider
            form_login:
                login_path: _security_login
                check_path: _security_login
                use_referer: true
            logout:
                path:   _security_logout
                target: home
            two-factor:
                auth_form_path: 2fa_login
                check_path: 2fa_login_check
                auth_code_parameter_name: _auth_code          # Name of the parameter containing the authentication code
                trusted_parameter_name: _trusted              # Name of the parameter containing the trusted flag
                multi_factor: true
                provider: our_db_provider
                prepare_on_login: true
                prepare_on_access_denied: true
                csrf_token_generator: security.csrf.token_manager
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /
    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/alwaysAccessible, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/2fa, role: IS_AUTHENTICATED_2FA_IN_PROGRESS }
        - { path: ^/members, role: ROLE_USER } # Secured member's area
